In [1]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [ ]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

2. Initialize an all one array with size 4X2.

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
np.zeros_like((2,2),dtype=float)

array([0., 0.])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
np.ones_like((2,2),dtype=float)

array([1., 1.])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
np.array(new_list)

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2.Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3.Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
np.eye(3,3) #creates one diagonal and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
array =np.random.random(30)
array.mean()

np.float64(0.5017950483479355)

5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
array = np.random.random((10, 10))
print(array)
print("Min:", array.min())
print("Max:", array.max())

[[0.11162919 0.76850531 0.10248062 0.49912786 0.40652169 0.73128349
  0.31121775 0.99164442 0.78928026 0.51729311]
 [0.45361533 0.65886527 0.91245038 0.07132109 0.56771133 0.45260264
  0.22141951 0.90472316 0.67942532 0.36937195]
 [0.59935333 0.26298434 0.24800491 0.85248015 0.50954269 0.24390114
  0.08584699 0.03630558 0.53860814 0.27086298]
 [0.84241767 0.48078324 0.89209088 0.91514406 0.5191705  0.54968029
  0.9811358  0.69490678 0.33213019 0.42574873]
 [0.758506   0.72510844 0.037949   0.17455548 0.48318456 0.73517579
  0.55178313 0.53087297 0.14836418 0.22037813]
 [0.61103659 0.72474524 0.09837781 0.16586532 0.6220097  0.31702075
  0.1063882  0.08498511 0.83613487 0.37286744]
 [0.32881974 0.78942081 0.66403683 0.84858479 0.64973897 0.14002597
  0.70507181 0.35231757 0.3640794  0.54457862]
 [0.83253643 0.66646867 0.97227352 0.50580127 0.16578987 0.84043438
  0.02344284 0.11499523 0.54803966 0.82448823]
 [0.53837112 0.05452269 0.65720022 0.16791775 0.5076854  0.21980264
  0.39066727

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1,2,0,0,4,0]
arr.reverse()
print(arr)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
arr = np.zeros((5, 5), dtype=int)

arr[0, :] = 1    # First row
arr[-1, :] = 1   # Last row

arr[:, 0] = 1    # First column
arr[:, -1] = 1   # Last column
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
matrix = np.zeros((8,8),dtype = int)
matrix[0:8:2 ,0:8:2] = 1
matrix[1:8:2 ,1:8:2] = 1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);



1. Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
np.add(x,y)



array([[ 6,  8],
       [10, 13]])

2. Subtract the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
np.subtract(x,y)


array([[-4, -4],
       [-4, -3]])

3. Multiply the array with any integers of your choice.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
np.multiply(x,y)

array([[ 5, 12],
       [21, 40]])

4. Find the square of each element of the array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
r1 = np.square(x)
r2 = np.square(y)
print(r1)
print(r2)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
r1 = np.dot(v,w)
r2 = np.dot(x,v)
r3 = np.dot(x,y)
print(r1)
print(r2)
print(r3)

219
[29 77]
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])
xy = np.concatenate((x,y))
print(xy)
vw = np.concatenate((v,w))
print(vw)


[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


--> The given error states that the input array must have same number of dimensions, x and v has different dimensions. To concatenate x and v we must have same dimensional shape, the error occured of x having 2 dimensional shape and v 1 dimensional shape.

In [ ]:
x = np.array([[1,2],[3,5]]) #2 dimensional shape
v = np.array([9,10]) # 1 dimensional shape
np.concatenate((x,v)) # both x and v must have same shape to concatenate.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:


In [ ]:
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

1. Prove A.A−1 = I.

In [ ]:
A = np.array([[3, 4],
              [7, 8]])
np.linalg.inv(A)


array([[-2.  ,  1.  ],
       [ 1.75, -0.75]])

2. Prove AB ̸= BA.

In [ ]:
np.dot(A, B), np.dot(B, A)

(array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]))

3. Prove (AB)

T = BTAT
.

In [ ]:
np.dot(A, B).T, np.dot(B.T, A.T)

(array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]))

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [ ]:
np.linalg.inv(np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])).dot(np.array([-1, -3, 9]))

array([ 2.,  1., -2.])